export enum NotionContentItemTypes {
  TEXT = 'text',
  TODO = 'todo',
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  TGL_H1 = 'tglH1',
  TGL_H2 = 'tglH2',
  TGL_H3 = 'tglH3',
  TGL_LIST = 'tglLi',
  BULL_LIST = 'bullLi',
  NUM_LIST = 'numLi',
  QUOTE = 'quote',
  WEB_BOOKMARK = 'webBookmark',
  IMAGE = 'image',
  VIDEO = 'video',
  DIVIDER = 'divider',
  PAGE_URL = 'pageUrl',
}
